package codegen

import (
	"strings"
	"testing"

	"github.com/waj/fango/internal/core"
	"github.com/waj/fango/internal/types"
)

// bytesADT builds the bundled Bytes' table rows as infer marks them.
func bytesADT(sup *types.Supply) *types.ADTInfo {
	con := &types.TCon{Unique: sup.NextUnique(), Name: "Bytes.Bytes"}
	adt := &types.ADTInfo{Con: con, Repr: types.ReprBytes}
	adt.Ctors = []*types.CtorInfo{{Name: "Bytes.Bytes", Index: 0, Result: con, Repr: types.ReprBytes}}
	return adt
}

// What the Bytes representation costs the backend: no emitted type, the
// runtime Go type everywhere the declared one would appear, the private
// constructor as the runtime empty value, and derived eq/show that keep the
// name and signature ordinary lowering gives them.
//
// Nothing in the bundled library reaches `$eq`/`$show` or matches on the
// private constructor, so those two paths have no fixture coverage; the Core
// below is the only way to reach them.
func TestBytesUsesTheRuntimeRepresentationEverywhere(t *testing.T) {
	sup := &types.Supply{}
	b := types.NewBuiltins(sup)
	adt := bytesADT(sup)
	bytesTy := adt.Con

	eqTmpl := "$eq($1, $2)"
	showTmpl := "$show($1)"
	natives := map[string]*types.NativeInfo{
		"Bytes.sameBytes": {Name: "Bytes.sameBytes", Module: "Bytes", Arity: 2, Template: &eqTmpl,
			Scheme: types.Scheme{Body: &types.TFun{Arg: bytesTy, Ret: &types.TFun{Arg: bytesTy, Ret: b.Bool}}}},
		"Bytes.showBytes": {Name: "Bytes.showBytes", Module: "Bytes", Arity: 1, Template: &showTmpl,
			Scheme: types.Scheme{Body: &types.TFun{Arg: bytesTy, Ret: b.String}}},
	}
	xs := &core.VarRef{Name: "xs", Local: true, Ty: bytesTy}
	ys := &core.VarRef{Name: "ys", Local: true, Ty: bytesTy}
	p := &core.Prog{
		Entry: "Main.main", ADTs: []*types.ADTInfo{adt}, Natives: natives,
		Defs: []core.Def{
			{Name: "Main.main", Owner: "Main", Params: []string{"_"}, ParamCaptures: []types.CaptureVar{1},
				Type: &types.TFun{Arg: b.Unit, Ret: b.Unit}, Body: &core.UnitLit{Ty: b.Unit}},
			{Name: "Bytes.same", Owner: "Bytes", Params: []string{"xs", "ys"}, ParamCaptures: []types.CaptureVar{1, 2},
				Type: &types.TFun{Arg: bytesTy, Ret: &types.TFun{Arg: bytesTy, Ret: b.Bool}},
				Body: &core.NativeCall{Name: "Bytes.sameBytes", Module: "Bytes", Args: []core.Expr{xs, ys}, Ty: b.Bool}},
			{Name: "Bytes.render", Owner: "Bytes", Params: []string{"xs"}, ParamCaptures: []types.CaptureVar{1},
				Type: &types.TFun{Arg: bytesTy, Ret: b.String},
				Body: &core.NativeCall{Name: "Bytes.showBytes", Module: "Bytes", Args: []core.Expr{xs}, Ty: b.String}},
			// `Bytes.empty`, and a match on the private constructor: one
			// nullary alternative, so the branch is taken unconditionally.
			{Name: "Bytes.empty", Owner: "Bytes", Type: bytesTy,
				Body: &core.App{CalleeKind: core.Ctor, Ctor: adt.Ctors[0], Ty: bytesTy}},
			{Name: "Bytes.width", Owner: "Bytes", Params: []string{"xs"}, ParamCaptures: []types.CaptureVar{1},
				Type: &types.TFun{Arg: bytesTy, Ret: b.Int},
				Body: &core.Case{Scrut: xs, Bind: "scrut", Ty: b.Int, Tree: &core.SwitchCtor{
					Scrut: "scrut", ADT: adt,
					Cases: []core.CtorCase{{Ctor: adt.Ctors[0], Tree: &core.Leaf{Body: &core.IntLit{Val: 7, Ty: b.Int}}}},
				}}},
		},
	}

	emit := func(u Unit) string {
		t.Helper()
		data, err := emitUnit(p, b, u, false)
		if err != nil {
			t.Fatal(err)
		}
		return string(data)
	}
	bytes := emit(Unit{Name: "Bytes"})
	emit(Unit{Name: "Main", Program: "Main", Entry: true}) // the entry unit must still emit

	for _, want := range []string{
		// The same exported names an emitted pair has, over the runtime type.
		"func EqT_Bytes_dot_Bytes(a, b fangort.Bytes) bool",
		"return fangort.BytesEq(a, b)",
		"func ShowT_Bytes_dot_Bytes(v fangort.Bytes, _ bool) string",
		"return fangort.BytesShow(v)",
		// Because the signature did not move, the call sites are unchanged.
		"EqT_Bytes_dot_Bytes(v_xs, v_ys)",
		"ShowT_Bytes_dot_Bytes(v_xs, false)",
		// The private constructor is the runtime empty value, and the
		// declared type appears as fangort.Bytes in every signature.
		"fangort.BytesEmpty()",
		"func V_Bytes_dot_render(v_xs fangort.Bytes) string",
	} {
		if !strings.Contains(bytes, want) {
			t.Errorf("generated Bytes is missing %q:\n%s", want, bytes)
		}
	}
	// A match on the one nullary constructor emits the branch itself, with no
	// discrimination of any kind.
	if !strings.Contains(bytes, "func V_Bytes_dot_width(v_xs fangort.Bytes) int64 {\n\tvar v_scrut fangort.Bytes = v_xs\n\treturn 7\n}") {
		t.Errorf("a match on Bytes did not compile to its only branch:\n%s", bytes)
	}
	for _, unwanted := range []string{"type T_Bytes_dot_Bytes", "isT_Bytes_dot_Bytes", "C_Bytes_dot_Bytes"} {
		if strings.Contains(bytes, unwanted) {
			t.Errorf("Bytes still emits %q; it has a runtime representation:\n%s", unwanted, bytes)
		}
	}
}
