package backend

import (
	"bytes"
	"testing"

	"github.com/waj/fango/internal/artifactframe"
	"github.com/waj/fango/internal/codegen"
)

func testRecord(path string) unitRecord {
	return unitRecord{Schema: emissionSchema, Unit: "Lib", Path: path, Implementation: "impl", Semantic: "sem", ABI: "abi",
		Linked: []linkedModule{{Module: "Basics", Semantic: "s", ABI: "a"}}}
}

// An artifact says what its unit was built from and what came out of it. The
// generated Go is not in it: that lives in the build tree, and the digest is
// what holds the file there to being the one this artifact describes.
func TestEmittedUnitRecordsItsSourceWithoutHoldingIt(t *testing.T) {
	file := codegen.File{Path: "modules/Lib/module.go", Data: []byte("package fangomod\n\nvar x = \"\xf0\x9f\x99\x82\"\n")}
	record := testRecord(file.Path)
	data := encodeUnit(record, file)
	got, ok := decodeUnit(data, record)
	if !ok || got != sourceDigest(file.Data) {
		t.Fatalf("round trip failed: %q %v", got, ok)
	}
	if bytes.Contains(data, file.Data) {
		t.Fatal("the artifact carries a second copy of the generated source")
	}
	if len(data) > 1024 {
		t.Errorf("artifact is %d bytes; it should hold a record, not a program", len(data))
	}
}

// A file that no longer hashes to what the artifact produced is not the file
// the artifact describes, whoever changed it.
func TestEmittedUnitRejectsAnAlteredGeneratedFile(t *testing.T) {
	file := codegen.File{Path: "modules/Lib/module.go", Data: []byte("package fangomod\n")}
	record := testRecord(file.Path)
	digest, ok := decodeUnit(encodeUnit(record, file), record)
	if !ok {
		t.Fatal("round trip failed")
	}
	tree := stubEmitted{file.Path: []byte("package fangomod // hand-edited\n")}
	if _, reused := (&Session{Emitted: tree}).reusable(file.Path, digest); reused {
		t.Fatal("an altered generated file was reused")
	}
	tree[file.Path] = file.Data
	if _, reused := (&Session{Emitted: tree}).reusable(file.Path, digest); !reused {
		t.Fatal("the file the artifact describes was not reused")
	}
	if _, reused := (&Session{}).reusable(file.Path, digest); reused {
		t.Fatal("reused generated bytes with no tree to read them from")
	}
}

type stubEmitted map[string][]byte

func (s stubEmitted) Source(path string) ([]byte, bool) {
	data, ok := s[path]
	return data, ok
}

// What an artifact was built from is part of it, so a slot holding bytes built
// from anything else is a miss rather than a wrong answer.
func TestEmittedUnitBuiltFromSomethingElseIsAMiss(t *testing.T) {
	file := codegen.File{Path: "modules/Lib/module.go", Data: []byte("package fangomod\n")}
	record := testRecord(file.Path)
	data := encodeUnit(record, file)
	otherPath := testRecord("modules/Other/module.go")
	otherOwn := testRecord(file.Path)
	otherOwn.Implementation = "other"
	otherLinked := testRecord(file.Path)
	otherLinked.Linked = []linkedModule{{Module: "Basics", Semantic: "moved", ABI: "a"}}
	extraLinked := testRecord(file.Path)
	extraLinked.Linked = append(append([]linkedModule(nil), extraLinked.Linked...), linkedModule{Module: "List", Semantic: "s", ABI: "a"})
	entryInputs := testRecord(file.Path)
	entryInputs.Entry, entryInputs.EntrySymbol = true, "Main.main"
	printMain := testRecord(file.Path)
	printMain.PrintMain = true
	for _, c := range []struct {
		name string
		want unitRecord
	}{
		{"another path", otherPath},
		{"an edited owner", otherOwn},
		{"a moved dependency contract", otherLinked},
		{"a widened closure", extraLinked},
		{"entry-only inputs", entryInputs},
		{"another main form", printMain},
	} {
		if _, ok := decodeUnit(data, c.want); ok {
			t.Errorf("%s was accepted", c.name)
		}
	}
	for _, c := range []struct {
		name string
		wire []byte
	}{
		{"truncated", data[:len(data)/2]},
		{"an artifact with no digest", artifactframe.Wrap(emissionKind, emissionSchema, []byte(`{"built":{"schema":3,"unit":"Lib","path":"modules/Lib/module.go","entry":false,"print_main":false,"implementation":"impl","semantic":"sem","abi":"abi","linked":[{"module":"Basics","semantic":"s","abi":"a"}],"entry_symbol":"","native_links":null,"intrinsics":null},"source":""}`))},
		{"no frame", file.Data},
	} {
		if _, ok := decodeUnit(c.wire, record); ok {
			t.Errorf("%s was accepted", c.name)
		}
	}
}
