// Package backend owns the owner-scoped machine lowering and Go emission
// boundary. Each owner is lowered and emitted from its own Core plus the
// installed dependency headers it links against, so an unchanged owner reuses
// its generated bytes while a changed dependency implementation rebuilds only
// what its contracts affect.
package backend

import (
	"runtime"
	"sort"
	"sync"
	"time"

	"github.com/waj/fango/internal/check"
	"github.com/waj/fango/internal/codegen"
	"github.com/waj/fango/internal/compilecache"
	"github.com/waj/fango/internal/compileevent"
	"github.com/waj/fango/internal/core"
	"github.com/waj/fango/internal/modules"
)

// Cache is the byte-storage seam for emitted units. A slot holds one owner's
// current record and a store replaces it; whether the generated file that
// record describes is still the right one is decided here. Missing, damaged,
// and unwritable entries are misses; the backend never reports them. Owners
// are stored as they are emitted, concurrently, so a cache must accept calls
// from several goroutines at once.
type Cache interface {
	Load(slot string) ([]byte, bool)
	Store(slot string, data []byte)
}

// Emitted is where an owner's generated bytes already are: the tree the driver
// is about to write, which is the only copy of them. Reuse needs both halves —
// a record that matches the graph and a file that still hashes to what that
// record produced — so a caller with no tree to read simply emits.
type Emitted interface {
	Source(path string) ([]byte, bool)
}

type Observer = compileevent.Observer

type Session struct {
	Observe      Observer
	Cache        Cache
	Emitted      Emitted
	DisableCache bool
}

// reusable is the generated file an artifact describes, when the tree still
// holds exactly it.
func (s *Session) reusable(path, digest string) ([]byte, bool) {
	if s == nil || s.Emitted == nil {
		return nil, false
	}
	source, ok := s.Emitted.Source(path)
	if !ok || len(source) == 0 || sourceDigest(source) != digest {
		return nil, false
	}
	return source, true
}

func (s *Session) timed(stage, owner string, start time.Time) {
	if s != nil {
		s.Observe.Timed(stage, owner, start)
	}
}

func (s *Session) begin(stage, owner string) time.Time {
	if s == nil {
		return time.Now()
	}
	return s.Observe.Begin(stage, owner)
}

// artifact reports a cache decision together with the bytes it moved.
func (s *Session) artifact(stage, owner string, start time.Time, bytes int) {
	if s != nil {
		s.Observe.Report(compileevent.Event{Stage: stage, Owner: owner, Duration: time.Since(start), Bytes: bytes})
	}
}

// EmitProject generates one Go file per owner. It is the module backend: the
// whole program is never lowered or emitted at once, and no dependency body is
// read. codegen.EmitProject remains the whole-program reference path the
// equivalence tests compare against.
func (s *Session) EmitProject(entry string, result *check.Result, units []codegen.Unit, printMain bool) ([]codegen.File, error) {
	if err := codegen.ValidateUnits(result.Program, units); err != nil {
		return nil, err
	}
	cache := s.Cache
	if cache == nil && !s.DisableCache {
		cache = compilecache.NewEmissionStore(entry)
	}
	summaries := moduleSummaries(result)
	links := entryNativeLinks(result.Program)
	closure := linkClosure(result.Graph)
	files := make([]codegen.File, 0, len(units))
	var work []emission
	for _, unit := range units {
		owner := ownerLabel(unit.Name)
		record, recorded := emissionRecord(result, unit, summaries, closure, links, printMain)
		slot := unitSlot(unit)
		if cache != nil {
			if !recorded {
				// An owner with nothing to compare against is emitted every
				// build. Saying so is what keeps the reuse tally a count over
				// every owner rather than over the ones a lookup was attempted
				// for.
				s.artifact("emitted-uncacheable", owner, time.Now(), 0)
			} else {
				lookupStart := time.Now()
				digest, read, found := loadUnit(cache, slot, record)
				if found {
					if source, hit := s.reusable(record.Path, digest); hit {
						s.artifact("emitted-cache-hit", owner, lookupStart, read+len(source))
						files = append(files, codegen.File{Path: record.Path, Data: source})
						continue
					}
				}
				s.artifact("emitted-cache-miss", owner, lookupStart, read)
			}
		}
		work = append(work, emission{unit: unit, owner: owner, record: record, recorded: recorded, slot: slot})
	}
	if err := s.emit(result, cache, work, printMain); err != nil {
		return nil, err
	}
	for _, w := range work {
		files = append(files, w.file)
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

// emission is one owner the cache could not supply.
type emission struct {
	unit     codegen.Unit
	owner    string
	record   unitRecord
	recorded bool
	slot     string

	file    codegen.File
	elapsed time.Duration
	err     error
	// stored is the artifact written for the owner, when it has a record.
	stored, storing time.Duration
	bytes           int
}

// emit lowers, emits, and stores the owners in work concurrently. Each owner
// is lowered from its own Core and the dependency headers it links against,
// so no two owners share mutable state. Events stay on the caller's goroutine
// and in owner order; each owner's emission and store times are their share
// of the phase's elapsed time, so the stages still add up to the build.
func (s *Session) emit(result *check.Result, cache Cache, work []emission, printMain bool) error {
	if len(work) == 0 {
		return nil
	}
	for i := range work {
		s.begin("emission", work[i].owner)
	}
	phase := time.Now()
	next := make(chan int, len(work))
	for i := range work {
		next <- i
	}
	close(next)
	var wg sync.WaitGroup
	for range min(runtime.GOMAXPROCS(0), len(work)) {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := range next {
				w := &work[i]
				start := time.Now()
				w.file, w.err = codegen.EmitUnit(codegen.UnitProgram(result.Program, w.unit), result.Checker.B, w.unit, printMain)
				w.elapsed = time.Since(start)
				if w.err == nil && w.recorded && cache != nil {
					start = time.Now()
					w.bytes = storeUnit(cache, w.slot, w.record, w.file)
					w.storing = time.Since(start)
				}
			}
		}()
	}
	wg.Wait()
	elapsed := time.Since(phase)
	var busy time.Duration
	for i := range work {
		if work[i].err != nil {
			return work[i].err
		}
		busy += work[i].elapsed + work[i].storing
	}
	share := func(d time.Duration) time.Duration {
		if busy == 0 {
			return 0
		}
		return time.Duration(float64(elapsed) * float64(d) / float64(busy))
	}
	for i := range work {
		s.Observe.Report(compileevent.Event{Stage: "emission", Owner: work[i].owner, Duration: share(work[i].elapsed)})
	}
	for i := range work {
		if work[i].recorded && cache != nil {
			s.Observe.Report(compileevent.Event{Stage: "emitted-cache-store", Owner: work[i].owner, Duration: share(work[i].storing), Bytes: work[i].bytes})
		}
	}
	return nil
}

// unitSlot names the one artifact this owner keeps. The entry answers to its
// file stem, which is also its sidecar name and the package it emits into,
// because a headerless entry has no module name of its own. The loader spells
// that stem once, on the unit.
func unitSlot(unit codegen.Unit) string {
	if unit.Entry {
		return compilecache.Slot(true, unit.Program)
	}
	return compilecache.Slot(false, unit.Name)
}

func ownerLabel(name string) string {
	if name == "" {
		return "<entry>"
	}
	return name
}

type linkSummary struct {
	semantic       string
	abi            string
	implementation string
}

func moduleSummaries(result *check.Result) map[string]linkSummary {
	out := make(map[string]linkSummary, len(result.Objects))
	for _, object := range result.Objects {
		if object.State == nil {
			continue
		}
		out[object.State.Name] = linkSummary{semantic: object.Semantic, abi: object.ABI, implementation: object.Implementation}
	}
	return out
}

// entryNativeLinks are the sidecar packages the entry package imports whether
// or not it calls them, so that every materialized sidecar is compiled.
func entryNativeLinks(p *core.Prog) []string {
	seen := map[string]bool{}
	for _, native := range p.Natives {
		if native.Template == nil && native.Module != "" {
			seen[native.Module] = true
		}
	}
	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// linkClosure is every module an owner can reach through its dependencies.
// Anything an owner's generated bytes can depend on is in it, including a type
// owner it never imports in source: that owner is reached through a dependency
// and is therefore a transitive dependency itself. Naming the closure rather
// than the whole graph is what lets two programs in one directory share an
// owner's bytes, and stops an unrelated module elsewhere in a program from
// invalidating them.
func linkClosure(graph *modules.Result) map[string][]string {
	if graph == nil {
		return nil
	}
	deps := make(map[string][]string, len(graph.Modules))
	for _, module := range graph.Modules {
		deps[module.Name] = module.Dependencies
	}
	out := make(map[string][]string, len(deps))
	for name := range deps {
		seen := map[string]bool{}
		var walk func(string)
		walk = func(current string) {
			for _, dep := range deps[current] {
				if dep == name || seen[dep] {
					continue
				}
				seen[dep] = true
				walk(dep)
			}
		}
		walk(name)
		reached := make([]string, 0, len(seen))
		for dep := range seen {
			reached = append(reached, dep)
		}
		sort.Strings(reached)
		out[name] = reached
	}
	return out
}

// emissionRecord names every input the owner's bytes depend on: its own
// runtime Core and declarations, the semantic and ABI contracts of every
// module it links against, the generated path and role, and the entry-only
// inputs. An owner whose closure is not fully summarized is emitted without
// being cached.
func emissionRecord(result *check.Result, unit codegen.Unit, summaries map[string]linkSummary, closure map[string][]string, links []string, printMain bool) (unitRecord, bool) {
	own, ok := summaries[unit.Name]
	if !ok || own.implementation == "" {
		return unitRecord{}, false
	}
	reached, known := closure[unit.Name]
	if !known {
		return unitRecord{}, false
	}
	linked := make([]linkedModule, 0, len(reached))
	for _, name := range reached {
		summary, ok := summaries[name]
		if !ok {
			return unitRecord{}, false
		}
		linked = append(linked, linkedModule{Module: name, Semantic: summary.semantic, ABI: summary.abi})
	}
	record := unitRecord{Schema: emissionSchema, Unit: unit.Name, Path: codegen.UnitPath(unit), Entry: unit.Entry, PrintMain: printMain,
		Implementation: own.implementation, Semantic: own.semantic, ABI: own.abi, Linked: linked}
	if unit.Entry {
		record.EntrySymbol = result.Program.Entry
		record.NativeLinks = links
		intrinsics := make([]string, 0, len(result.Program.Intrinsics))
		for name, on := range result.Program.Intrinsics {
			if on {
				intrinsics = append(intrinsics, name)
			}
		}
		sort.Strings(intrinsics)
		record.Intrinsics = intrinsics
	}
	return record, true
}
