// Package backend owns the owner-scoped machine lowering and Go emission
// boundary. Each owner is lowered and emitted from its own Core plus the
// installed dependency headers it links against, so an unchanged owner reuses
// its generated bytes while a changed dependency implementation rebuilds only
// what its contracts affect.
package backend

import (
	"fmt"
	"sort"

	"github.com/waj/fango/internal/check"
	"github.com/waj/fango/internal/codegen"
	"github.com/waj/fango/internal/compilecache"
	"github.com/waj/fango/internal/core"
	machineir "github.com/waj/fango/internal/machine"
)

// Cache is the byte-storage seam for emitted units. Missing, damaged, and
// unwritable entries are misses; the backend never reports them.
type Cache interface {
	Load(key string) ([]byte, bool)
	Store(key string, data []byte)
}

type Observer func(stage, owner string)

type Session struct {
	Observe      Observer
	Cache        Cache
	DisableCache bool
}

func (s *Session) event(stage, owner string) {
	if s != nil && s.Observe != nil {
		s.Observe(stage, owner)
	}
}

// EmitProject generates one Go file per owner. It is the module backend: the
// whole program is never lowered or emitted at once, and no dependency body is
// read. codegen.EmitProject remains the whole-program reference path the
// equivalence tests compare against.
func (s *Session) EmitProject(entry string, result *check.Result, units []codegen.Unit, printMain bool) ([]codegen.File, error) {
	if err := codegen.ValidateUnits(result.Program, units); err != nil {
		return nil, err
	}
	cache := s.Cache
	if cache == nil && !s.DisableCache {
		cache = compilecache.NewEmissionStore(entry)
	}
	summaries := moduleSummaries(result)
	links := entryNativeLinks(result.Program)
	files := make([]codegen.File, 0, len(units))
	for _, unit := range units {
		owner := ownerLabel(unit.Name)
		key, keyed := emissionKey(result, unit, summaries, links, printMain)
		if keyed && cache != nil {
			if data, hit := loadUnit(cache, key, codegen.UnitPath(unit)); hit {
				s.event("emitted-cache-hit", owner)
				files = append(files, codegen.File{Path: codegen.UnitPath(unit), Data: data})
				continue
			}
			s.event("emitted-cache-miss", owner)
		}
		unitProg := codegen.UnitProgram(result.Program, unit)
		s.event("lowering", owner)
		mp, lowerErrs := machineir.LowerUnit(unitProg, unit.Name, result.Checker.B)
		if len(lowerErrs) != 0 {
			return nil, fmt.Errorf("machine lowering failed in module %s: %v", owner, lowerErrs[0])
		}
		s.event("emission", owner)
		file, err := codegen.EmitUnit(unitProg, mp, result.Checker.B, unit, printMain)
		if err != nil {
			return nil, err
		}
		if keyed && cache != nil {
			storeUnit(cache, key, file)
		}
		files = append(files, file)
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

func ownerLabel(name string) string {
	if name == "" {
		return "<entry>"
	}
	return name
}

type linkSummary struct {
	semantic       string
	abi            string
	implementation string
}

func moduleSummaries(result *check.Result) map[string]linkSummary {
	out := make(map[string]linkSummary, len(result.Objects))
	for _, object := range result.Objects {
		if object.State == nil {
			continue
		}
		out[object.State.Name] = linkSummary{semantic: object.Semantic, abi: object.ABI, implementation: object.Implementation}
	}
	return out
}

// entryNativeLinks are the sidecar packages the entry package imports whether
// or not it calls them, so that every materialized sidecar is compiled.
func entryNativeLinks(p *core.Prog) []string {
	seen := map[string]bool{}
	for _, native := range p.Natives {
		if native.Template == nil && native.Module != "" {
			seen[native.Module] = true
		}
	}
	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// emissionKey names every input the owner's bytes depend on: its own runtime
// Core and declarations, the transitive semantic and ABI contracts of the
// modules it links against — which carry their own dependencies' contracts, so
// a transitive type owner cannot change unnoticed — the Go edges it retains,
// its role, and the entry-only inputs. An owner whose graph is not fully
// summarized is emitted without being cached.
func emissionKey(result *check.Result, unit codegen.Unit, summaries map[string]linkSummary, links []string, printMain bool) (string, bool) {
	own, ok := summaries[unit.Name]
	if !ok || own.implementation == "" {
		return "", false
	}
	parts := []string{"emitted-unit", fmt.Sprint(emissionSchema), unit.Name, own.implementation, own.semantic, own.abi,
		fmt.Sprint(unit.Entry), fmt.Sprint(printMain)}
	imports := append([]string(nil), unit.Imports...)
	sort.Strings(imports)
	for _, name := range imports {
		summary, known := summaries[name]
		if !known {
			return "", false
		}
		parts = append(parts, "import", name, summary.semantic, summary.abi)
	}
	// Every other installed module contributes the headers this owner links
	// against, including type owners it never imports in source.
	others := make([]string, 0, len(summaries))
	for name := range summaries {
		others = append(others, name)
	}
	sort.Strings(others)
	for _, name := range others {
		summary := summaries[name]
		parts = append(parts, "linked", name, summary.semantic, summary.abi)
	}
	if unit.Entry {
		parts = append(parts, "entry", result.Program.Entry)
		parts = append(parts, "native")
		parts = append(parts, links...)
		intrinsics := make([]string, 0, len(result.Program.Intrinsics))
		for name, on := range result.Program.Intrinsics {
			if on {
				intrinsics = append(intrinsics, name)
			}
		}
		sort.Strings(intrinsics)
		parts = append(parts, intrinsics...)
	}
	return digest(parts...), true
}
